In [ ]:
%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
AVG_RATING20=hc.sql("SELECT name, COUNT(name) AS name_count, AVG(stars) AS avg_rating FROM business GROUP BY name ORDER BY name_count DESC LIMIT 20")
z.show(AVG_RATING20)


%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
top_avg_cities = hc.sql("SELECT city, AVG(stars) AS avg_rating FROM business WHERE stars IS NOT NULL GROUP BY city ORDER BY avg_rating DESC LIMIT 30")
z.show(top_avg_cities)

%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
mexican_restaurant =hc.sql("SELECT name ,stars, address, categories AS mexican_restaurants FROM business WHERE categories = 'Restaurants, Mexican' OR categories = 'Mexican, Restaurants' ORDER BY stars DESC LIMIT 10")
z.show(mexican_restaurant)

%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
vietnamese_restaurant =hc.sql("SELECT name ,stars, address, categories AS vitnamese_restaurants FROM business WHERE categories = 'Vietnamese, Restaurants' OR categories = 'Restaurants, Vietnamese' ORDER BY stars DESC LIMIT 10")
z.show(vietnamese_restaurant)

%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
chinese_restaurant =hc.sql("SELECT name ,stars, address, categories AS chinese_restaurants FROM business WHERE categories = 'Restaurants, Chinese' OR categories = 'Chinese, Restaurants' ORDER BY stars DESC LIMIT 10")
z.show(chinese_restaurant)

%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)


five_stars_merchs = hc.sql("SELECT name, COUNT(*) AS five_star_reviews FROM business WHERE stars = 5.0 GROUP BY name  ORDER BY five_star_reviews DESC LIMIT 20")
z.show(five_stars_merchs)


%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
best_businesses = hc.sql("SELECT name, state, city, review_count, stars FROM business WHERE review_count > 100 AND stars = 5 ORDER BY review_count DESC LIMIT 20 ")
z.show(best_businesses)

%pyspark
from pyspark.sql import HiveContext
from pyspark.sql.functions import *

hcx = HiveContext(sc)

business_df = hcx.table('business')

# Group by city and calculate average review count and star rating
city_stats = business_df.groupBy('city').agg(
    avg('review_count').alias('avg_review_count'),
    avg('stars').alias('avg_stars')
)

# Group by state and calculate average review count and star rating
state_stats = business_df.groupBy('state').agg(
    avg('review_count').alias('avg_review_count'),
    avg('stars').alias('avg_stars')
)

# Show the distribution of review counts and stars by city
print("Distribution by City:")
z.show(city_stats)

# Show the distribution of review counts and stars by state
print("Distribution by State:")
z.show(state_stats)

%pyspark
from pyspark.sql import HiveContext
from pyspark.sql.functions import *

hcx = HiveContext(sc)

business_df = hcx.table('business')

# Group by business_id and calculate average review count and average stars
business_aggregated = business_df.groupBy('business_id').agg(
    avg('review_count').alias('avg_review_count'),
    avg('stars').alias('avg_stars')
)

# Show the aggregated data
z.show(business_aggregated)

%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
mst_comm_merchs = hc.sql("SELECT name, COUNT(name) as name_count FROM business GROUP BY name ORDER BY name_count DESC LIMIT 20")
 
z.show(mst_comm_merchs)
%pyspark
from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
most_10_cities = hc.sql("SELECT city, COUNT(city) as city_count FROM business GROUP BY city ORDER BY city_count  DESC LIMIT 10")
z.show(most_10_cities)

%pyspark

from pyspark.sql import HiveContext
 
hc = HiveContext(sc)
top_5_states = hc.sql("SELECT state, COUNT(state) as state_count FROM business GROUP BY state ORDER BY state_count  DESC LIMIT 5")
z.show(top_5_states)

%pyspark
from pyspark.sql import HiveContext
AVG_RATING20=hc.sql("SELECT name, COUNT(name) AS name_count, AVG(stars) AS avg_rating FROM business GROUP BY name ORDER BY name_count DESC LIMIT 20")



z.show(AVG_RATING20)

%pyspark
from pyspark.sql import HiveContext
hc = HiveContext(sc)
total_categories=hc.sql("SELECT COUNT(DISTINCT categories) as total_categories FROM business LIMIT 10")
z.show(total_categories)

%pyspark
from pyspark.sql import HiveContext
hc = HiveContext(sc)
highest_f_categories=hc.sql("SELECT categories, COUNT (*) AS frequency FROM business GROUP BY categories ORDER BY frequency DESC LIMIT 10")
z.show(highest_f_categories)

%pyspark
from pyspark.sql import HiveContext
hc = HiveContext(sc)
top20_merchants = hc.sql("SELECT name, COUNT(*) as five_star_reviews FROM business WHERE stars = 5.0 GROUP BY name ORDER BY five_star_reviews DESC LIMIT 20")

z.show(top20_merchants )
%pyspark
from pyspark.sql import HiveContext
hc = HiveContext(sc)
review_count_restaurants_cn = hc.sql("SELECT categories, stars, COUNT(*) AS count FROM business WHERE categories LIKE '%Restaurants, Chinese%' GROUP BY categories, stars ORDER BY stars DESC")
review_count_restaurants_vn = hc.sql("SELECT categories, stars, COUNT(*) AS count FROM business WHERE categories LIKE '%Restaurants, Vietnamese%' GROUP BY categories, stars ORDER BY stars DESC")
review_count_restaurants_mx = hc.sql("SELECT categories, stars, COUNT(*) AS count FROM business WHERE categories LIKE '%Restaurants, Mexican%' GROUP BY categories, stars ORDER BY stars DESC")
review_count_restaurants_us = hc.sql("SELECT categories, stars, COUNT(*) AS count FROM business WHERE categories LIKE '%Restaurants, American%' GROUP BY categories, stars ORDER BY stars DESC")
z.show(review_count_restaurants_cn)
z.show(review_count_restaurants_vn)
z.show(review_count_restaurants_mx)
z.show(review_count_restaurants_us)